### ISSUE TITLE
Timeouts when running migrations

### ISSUE THREAD

**Issue by afsheenb** [hsgubert/cassandra_migrations#43]
When attempting to run a test migration against our production cluster, rake usually exits due to a transient error of some sort shortly after the migration is begun. start_native_transport is set to true on all of my nodes, and I've tested both creating my fields and tables manually and also writng to our cql cluster programatically at the same time - it appears it's only this utility that's timing out connections to cassandra. 

Sanitized example of a simple cassandra:create timeing out:

root@ec2:/usr/src/data-store/cassandra-migrations# rake cassandra:create RAILS_ENV=testing --trace
*\* Invoke cassandra:create (first_time)
*\* Execute cassandra:create
rake aborted!
CassandraMigrations::Errors::UnexistingKeyspaceError: Keyspace test does not exist. Run rake cassandra:create.
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/cassandra.rb:54:in `rescue in use'
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/cassandra.rb:51:in`use'
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/cassandra/keyspace_operations.rb:17:in `create_keyspace!'
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/railtie/tasks.rake:15:in`rescue in block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/railtie/tasks.rake:11:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in`call'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in`each'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:179:in`block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:172:in`invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:150:in`invoke_task'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in`each'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:115:in`run_with_threads'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:78:in`block in run'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:75:in`run'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/bin/rake:23:in`load'
/usr/local/rvm/gems/ruby-2.1.2/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in`eval'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Cql::QueryError: Keyspace 'adx' does not exist
/usr/local/rvm/gems/ruby-2.1.2/gems/cql-rb-2.0.0/lib/cql/client/client.rb:541:in`use'
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/cassandra.rb:52:in `use'
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/cassandra/keyspace_operations.rb:17:in`create_keyspace!'
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/railtie/tasks.rake:15:in `rescue in block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/railtie/tasks.rake:11:in`block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in`block in execute'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in`execute'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in`mon_synchronize'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:165:in`invoke'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in`block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in`block in top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:100:in`top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:176:in`standard_exception_handling'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/bin/rake:33:in`<top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.1.2/bin/rake:23:in`<main>'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in`<main>'
CassandraMigrations::Errors::UnexistingKeyspaceError: Keyspace adx does not exist. Run rake cassandra:create.
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/cassandra.rb:54:in `rescue in use'
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/cassandra.rb:51:in`use'
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/cassandra.rb:19:in `start!'
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/railtie/tasks.rake:12:in`block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in`block in execute'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in`execute'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in`mon_synchronize'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:165:in`invoke'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in`block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in`block in top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:100:in`top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:176:in`standard_exception_handling'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/bin/rake:33:in`<top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.1.2/bin/rake:23:in`<main>'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in`<main>'
Cql::QueryError: Keyspace 'test' does not exist
/usr/local/rvm/gems/ruby-2.1.2/gems/cql-rb-2.0.0/lib/cql/client/client.rb:541:in `use'
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/cassandra.rb:52:in`use'
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/cassandra.rb:19:in `start!'
/usr/local/rvm/gems/ruby-2.1.2/gems/cassandra_migrations-0.1.0/lib/cassandra_migrations/railtie/tasks.rake:12:in`block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in`block in execute'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in`execute'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in`mon_synchronize'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:165:in`invoke'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in`block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in`block in top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:100:in`top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:176:in`standard_exception_handling'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/bin/rake:33:in`<top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.1.2/bin/rake:23:in`<main>'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in`<main>'
Tasks: TOP => cassandra:create

I would assume that this is due to a misconfiguration on our side, but I'm not certain. Has anyone else reported similar issues?

Cheers!

**Comment by gabosgab** [comment]
PS: I ran into this exact issue when running unit tests with the Timecop gem.  It makes the connection think it has timed out if you travel too much.
