### ISSUE TITLE
rake aborted! Don't know how to build task 'cassandra:setup'

### ISSUE THREAD

**Issue by vhall98** [hsgubert/cassandra_migrations#64]
Hi, after installing cassandra_migration gem and executing prepare_for_cassandra and modifying the newly create config/cassandra.yaml, when I run rake cassandra:setup, I get this error:

rake aborted!
Don't know how to build task 'cassandra:setup'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task_manager.rb:63:in `[]'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:152:in `invoke_task'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:107:in `block (2 levels) in top_level'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:107:in `each'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:107:in `block in top_level'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:116:in `run_with_threads'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:181:in `standard_exception_handling'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
C:/RailsInstaller/Ruby2.1.0/bin/rake:23:in `load'
C:/RailsInstaller/Ruby2.1.0/bin/rake:23:in `<main>'

I also ran rake cassandra:create, rake cassandra:migrate and drop and the same error occurs. I added put statements in application.rb and task_manager but no luck.  Can you please provide some guidance on this issue?  Thanks!

Rails 4.2.1
ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]

**Comment by vhall98** [comment]
This issue occurs when using ruby 2.1.5p273 and does not occur when using ruby 2.2.1p85

**Comment by bsbodden** [comment]
Where you able to trace it to specific method/line that blows up on that Ruby version?

**Comment by vhall98** [comment]
The problem was I needed to include gem cassandra_migration inside my
Gemfile instead of installing the gem at the prompt. After I did that it
worked. Will close issue and thanks for resp

- sent from Milky Way Galaxy -
