### ISSUE TITLE
What's the status on on Cassandra 3.x support?

### ISSUE THREAD

**Issue by ckhall** [hsgubert/cassandra_migrations#74]
Cassandra 3.2.1 was recently released and Cassandra 3.0.2 seems to be the latest "stable" version after 2.2.  Datatastax ruby driver has a new release, 3.0.0.beta1, which is supposed to support Cassandra 2.2 and 3.0.  Are there plans to move to this new driver and become compatible with Cassandra 3.x?

Thanks for all your work on this gem.

**Comment by bsbodden** [comment]
Just upped the driver versions.
