### ISSUE TITLE
Allow Users to alter_table

### ISSUE THREAD

**Issue by gabosgab** [hsgubert/cassandra_migrations#75]
Currently there is no way to alter a table, would be great to support alter_table command.

**Comment by eprothro** [comment]
@gabosgab, just FYI, unsupported commands are still executable within a versioned migration:

https://github.com/hsgubert/cassandra_migrations/wiki/Migrations-DSL#unsupported-operations

**Comment by gabosgab** [comment]
Yeah, that's what I've been doing for now.  Just wish it was a first class citizen like Rails treats their migrations.
