### ISSUE TITLE
Testing/Enhancements to work with Cassandra 3.x

### ISSUE THREAD

**Issue by bsbodden** [hsgubert/cassandra_migrations#83]
There are a lot of changes in the system schemas of C* 3.x as well as changes in the latest Datastax Drivers that need to be tested and incorporated. Supporting cassandra_migrations for both C* < 3.0 and >= 3.0 might involve some conditionals (if the driver is not handling the differences gracefully)

**Comment by bsbodden** [comment]
Upped the driver version to 3.0.0, tested with C* 3.3, @devdame @cosgroveb @sstgithub @eprothro Could you test with your C* versions and report here? Thx!

**Comment by cosgroveb** [comment]
Hey @bsbodden.. The gem with driver version 3.0.0 works for our one very simple migration against DSE 4.8.5/Cassandra 2.1.13.1131.

**Comment by eprothro** [comment]
I have 50 migrations I can try against DSE=>c* 2.x as well as against c* 3.0.x. Will try to get to that this week.

-Evan

**Comment by sstgithub** [comment]
Thanks for the upgrade @bsbodden! We're currently using a forked version so I'll have to update that and then will get back to you asap

**Comment by eprothro** [comment]
@bsbodden you want us to test against master?

**Comment by eprothro** [comment]
@bsbodden first blush is that my migrations worked with

* `cassandra_migrations` 227563c3528f44c607400e8d040c05e33b87b231
* `cassandra-driver` 3.0.0
* `cassandra` 3.5

and

* `cassandra_migrations` 227563c3528f44c607400e8d040c05e33b87b231
* `cassandra-driver` 3.0.0
* `DSE` 4.8.4 (`cassandra` 2.1.x)

If I run into issues with continued testing, I'll update you here.

**Comment by eprothro** [comment]
@bsbodden what about a 0.2.6 release to allow easier testing of this? rails dependency changes (#86) force me to point at the repo -- I don't want to commit that code ;)

**Comment by bsbodden** [comment]
I just finished testing a few other projects. Will push a release today after a few more patches.

**Comment by sstgithub** [comment]
@bsbodden tested with 3.0, queries no longer work since column type determination is different: See PR #89
