### ISSUE TITLE
Rails versions other than 3.2.x no longer supported w/runtime dependency change

### ISSUE THREAD

**Issue by devdame** [hsgubert/cassandra_migrations#85]
The last release introduced a line in the gemspec that requires Rails `~> 3.2`, which makes the gem incompatible with all non-3.2 versions of Rails.  Right now, running a bundle on my app using Rails 4.2.5.2 this errors out citing incompatible Rails versions.  When we changed it back to `>= 3.2` locally this issue was fixed.  Not sure if this was an intentional change or if it accidentally got changed when switching to `add_runtime_dependency`.  If intentional, is there a reason behind this?

The exact line causing the issue: https://github.com/hsgubert/cassandra_migrations/commit/c383352253bcc87c41c8083d24795b1219985868#diff-c6f6c48b08bbdab5ce11ae086ea075cbR28

Thanks again! :birthday:

**Comment by bsbodden** [comment]
Oh that's weird. I think that I copy and pasted the bundler suggestion on not restricting the version, go ahead and revert it and I can cut another gem (I'll probably evaluate the PRs that landed since that version and then release again and yank this one then)

**Comment by bsbodden** [comment]
@devdame thanks for the fix!
